#eu acho que o application.properties é o mesmo que o .env


spring.application.name=produto

#informa qual o perfil está ativo. ele busca um arquivo como nome application-oNomeQueEuDer e nesse caso foi test, pois é um ambiente de teste
spring.profiles.active=test  

#habilita o spring a gerenciar as transações até a a camada de Service e não ir além dela
sprinp.jpa.open-in-view=false

security.client-id=${CLIENT_ID:myclientid}
security.client-secret=${CLIENT_SECRET:myclientsecret}
#duração do token
security.jwt.duration=${JWT_DURATION:86400} 
#cors
cors.origins=${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}