#eu acho que o application.properties e o mesmo que o .env


spring.application.name=produto

#informa qual o perfil esta ativo. ele busca um arquivo como nome application-oNomeQueEuDer e nesse caso foi test, pois e um ambiente de teste
spring.profiles.active=prod

#habilita o spring a gerenciar as transacoes ate a a camada de Service e nao ir alem dela
sprinp.jpa.open-in-view=false

#usuario
security.client-id=${CLIENT_ID:myclientid}
#senha
security.client-secret=${CLIENT_SECRET:myclientsecret}
#duracao do token
security.jwt.duration=${JWT_DURATION:86400} 
#cors
cors.origins=${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}

#esse e o tempo que eu defini pro token durar
email.password-recover.token.minutes:30
#esse e o link para o usuario trocar a senha
email.password-recover.uri=hhtp://meusite.com.br/recover-password/ 